# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ master ]
    
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build using Maven
        run: mvn package
